# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Rasterize_with_attribute
                                 A QGIS plugin
 This plugin is an alternative to the GDAL "Rasterize (overwrite with attribute)" tool, available from the ToolBox, with the advantage of creating a new temporary raster for the result, unlike the original tool that modifies the input raster without previously creating a copy of it.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-26
        copyright            : (C) 2025 by Antonio Sobral Almeida
        email                : 66124.almeida@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Antonio Sobral Almeida'
__date__ = '2025-07-26'
__copyright__ = '(C) 2025 by Antonio Sobral Almeida'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Rasterize_with_attribute class from file Rasterize_with_attribute.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rasterize_with_attribute import Rasterize_with_attributePlugin
    return Rasterize_with_attributePlugin()
